snake prueba4

diff --git a/.github/workflows/snake.yml b/.github/workflows/snake.yml
--- a/.github/workflows/snake.yml
+++ b/.github/workflows/snake.yml
@@ -1,12 +1,12 @@
 name: Generate snake animation
 
 on:
-  schedule:
-    - cron: "0 */12 * * *" # Ejecuta cada 12 horas
-  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo
+  schedule: 
+    - cron: "* */12 * * *"
+  workflow_dispatch:
   push:
     branches:
-      - main  # Solo se activa al hacer push en la rama main
+      - master
 
 jobs:
   generate:
@@ -16,19 +16,25 @@ jobs:
     timeout-minutes: 5
 
     steps:
-      - name: Check out the repository
-        uses: actions/checkout@v3
+      - name: Check out repository
+        uses: actions/checkout@v2
+
+      - name: Create dist directory
+        run: mkdir -p dist
 
       - name: Generate snake.svg
         uses: Platane/snk/svg-only@v3
         with:
           github_user_name: ${{ github.repository_owner }}
-          svg_out_path: dist/snake.svg?palette=github-dark
+          output: dist/snake.svg
+
+      - name: Check generated files
+        run: ls -R dist || echo "Directory not found or empty"
 
       - name: Push snake.svg to the output branch
         uses: crazy-max/ghaction-github-pages@v3.1.0
         with:
-          target_branch: output  # Subir a la rama output
+          target_branch: output
           build_dir: dist
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
